---
- hosts: local
  connection: local

  tasks:
    - name: run date in 2 minutes
      at:
        command: /bin/logger 'AT task ran from Ansible'
        count: 2
        units: minutes
        unique: yes
      environment:
        PWD: /root

...
