---
- hosts: local
  connection: local
  gather_facts: false

  tasks:
    - name: run date in 2 minutes
      at:
        command: /bin/logger 'AT task ran from Ansible'
        count: 2
        units: minutes
        unique: yes
      environment:
        PWD: /root

    - name: copy job file
      copy:
        src: ./myjob.txt
        dest: /root/myjob.txt

    - name: testing with shell mod
      shell:
        chdir: /root
        cmd: at now + 2 min -f myjob.txt

    - name: cleanup job file
      file:
        src: /root/myjob.txt
        state: absent

...
