---
- hosts: local
  connection: local

  tasks:
    - name: run date in 2 minutes
      at:
        command: /bin/date >/dev/null
        count: 2
        units: minutes
        unique: yes
      register: result

    - name: test at job ran
      syslogger:
        msg: "AT task ran with result= {{ result.stdout_lines }}"
...
